# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('date_of_registration', models.DateField(auto_now_add=True)),
                ('street_address_1', models.CharField(max_length=60)),
                ('street_address_2', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('website', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('meals', models.CharField(max_length=30)),
                ('billing_firstname', models.CharField(max_length=30)),
                ('billing_lastname', models.CharField(max_length=30)),
                ('card_type', models.CharField(max_length=16)),
                ('card_csv', models.CharField(max_length=4)),
                ('exp_year', models.CharField(max_length=4)),
                ('exp_month', models.CharField(max_length=2)),
                ('session1', models.CharField(max_length=35)),
                ('session2', models.CharField(max_length=35)),
                ('session3', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('session', models.CharField(max_length=7)),
                ('room', models.CharField(max_length=2)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
    ]
