# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170508_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='session1',
            field=models.CharField(choices=[('Workshop A', 'Workshop A'), ('Workshop B', 'Workshop B'), ('Workshop C', 'Workshop C')], max_length=35),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='session2',
            field=models.CharField(choices=[('Workshop D', 'Workshop D'), ('Workshop E', 'Workshop E'), ('Workshop F', 'Workshop F')], max_length=35),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='session3',
            field=models.CharField(choices=[('Workshop G', 'Workshop G'), ('Workshop H', 'Workshop H'), ('Workshop I', 'Workshop I')], max_length=35),
        ),
    ]
