# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170509_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='end',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='room',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='session',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='start',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
